FROM node:20-alpine AS build

WORKDIR /app

ARG VITE_BACKEND_BASE_URL=/api
ARG VITE_GENERATE_PROPOSAL_BASE_URL=/api
ARG VITE_LOGIN_ENDPOINT=/login
ARG VITE_ONBOARD_COMPANY_ENDPOINT=/onboard-company
ARG VITE_UPLOAD_PDF_ENDPOINT=/upload-pdf
ARG VITE_GENERATE_PROPOSAL_ENDPOINT=/generate-proposal
ARG VITE_CHECK_PROPOSAL_FORMAT_ENDPOINT=/check-proposal-format
ARG VITE_PROCUREMENT_ORCHESTRATION_ENDPOINT=/procurement-orchestration
ARG VITE_TRIGGER_PROCUREMENT_ORCHESTRATION_ENDPOINT=/trigger-procurement-orchestration

ENV VITE_BACKEND_BASE_URL=$VITE_BACKEND_BASE_URL
ENV VITE_GENERATE_PROPOSAL_BASE_URL=$VITE_GENERATE_PROPOSAL_BASE_URL
ENV VITE_LOGIN_ENDPOINT=$VITE_LOGIN_ENDPOINT
ENV VITE_ONBOARD_COMPANY_ENDPOINT=$VITE_ONBOARD_COMPANY_ENDPOINT
ENV VITE_UPLOAD_PDF_ENDPOINT=$VITE_UPLOAD_PDF_ENDPOINT
ENV VITE_GENERATE_PROPOSAL_ENDPOINT=$VITE_GENERATE_PROPOSAL_ENDPOINT
ENV VITE_CHECK_PROPOSAL_FORMAT_ENDPOINT=$VITE_CHECK_PROPOSAL_FORMAT_ENDPOINT
ENV VITE_PROCUREMENT_ORCHESTRATION_ENDPOINT=$VITE_PROCUREMENT_ORCHESTRATION_ENDPOINT
ENV VITE_TRIGGER_PROCUREMENT_ORCHESTRATION_ENDPOINT=$VITE_TRIGGER_PROCUREMENT_ORCHESTRATION_ENDPOINT

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ .
RUN npm run build

FROM nginx:1.27-alpine

COPY deployment/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
