"""
normaliser.py

Converts the raw dict output from EITHER docling_parser.py OR fallback_parser.py
into the unified ParsedDocument Pydantic model.

Why this exists:
  Both parsers return the same dict shape but there can be small inconsistencies
  (missing keys, None values, empty strings). The normaliser handles all of that
  defensively so Phase 2 (chunking) always receives clean, validated data.

  Phase 2 should NEVER import from docling_parser or fallback_parser directly.
  It only ever works with ParsedDocument objects produced here.
"""

import logging
from .models.parsed_document import (
    ParsedDocument,
    ParsedSection,
    ParsedTable,
    ParserUsed,
)

logger = logging.getLogger(__name__)


# ─── TABLE NORMALISER ─────────────────────────────────────────────────────────

def _normalise_table(raw: dict) -> ParsedTable:
    """
    Converts a raw table dict into a ParsedTable model.
    Handles missing keys defensively.
    """
    return ParsedTable(
        table_id      = raw.get("table_id", "t_000"),
        page_number   = int(raw.get("page_number", 1)),
        section_title = str(raw.get("section_title", "Unknown")),
        headers       = [str(h) for h in raw.get("headers", [])],
        rows          = [
            [str(cell) for cell in row]
            for row in raw.get("rows", [])
        ],
        raw_markdown  = str(raw.get("raw_markdown", "")),
    )


# ─── SECTION NORMALISER ───────────────────────────────────────────────────────

def _normalise_section(raw: dict) -> ParsedSection:
    """
    Converts a raw section dict into a ParsedSection model.
    Recursively normalises children sections.

    Cleans content:
      - Strips leading/trailing whitespace
      - Collapses 3+ consecutive newlines to 2 (avoids huge blank gaps in chunks)
    """
    import re

    content = str(raw.get("content", "")).strip()
    # Collapse excessive blank lines
    content = re.sub(r"\n{3,}", "\n\n", content)

    return ParsedSection(
        section_id = raw.get("section_id", "s_000"),
        title      = str(raw.get("title", "Untitled")).strip(),
        level      = max(1, min(int(raw.get("level", 1)), 3)),  # clamp 1–3
        page_start = int(raw.get("page_start", 1)),
        page_end   = int(raw.get("page_end", raw.get("page_start", 1))),
        content    = content,
        tables     = [_normalise_table(t) for t in raw.get("tables", [])],
        children   = [_normalise_section(child) for child in raw.get("children", [])],
    )


# ─── FLAT TABLE LIST BUILDER ──────────────────────────────────────────────────

def _collect_all_tables(sections: list[ParsedSection]) -> list[ParsedTable]:
    """
    Walks the full section tree and collects every ParsedTable into a flat list.
    This builds the all_tables field of ParsedDocument for quick access.

    Note: these are the SAME table objects already inside sections —
    just also accessible without walking the tree.
    """
    tables = []

    def walk(section_list):
        for section in section_list:
            tables.extend(section.tables)
            walk(section.children)

    walk(sections)
    return tables


# ─── MAIN NORMALISE FUNCTION ──────────────────────────────────────────────────

def normalise(
    raw_output:     dict,
    doc_id:         str,
    file_name:      str,
    parser_used:    ParserUsed,
    metadata:       dict | None = None,
) -> ParsedDocument:
    """
    Converts raw parser output into a fully validated ParsedDocument.

    Args:
        raw_output:     Dict returned by parse_with_docling() or parse_with_fallback()
                        Expected keys: sections, all_tables, total_pages, language_hint
        doc_id:         Unique document ID (generated by pipeline.py at upload time)
        file_name:      Original filename of the uploaded PDF
        parser_used:    ParserUsed.DOCLING or ParserUsed.FALLBACK
        quality_report: QualityReport from quality_checker.py
        metadata:       Optional dict of extra info (parse time, file size, etc.)

    Returns:
        ParsedDocument — the unified, validated output of Phase 1.
        This is what pipeline.py returns and what Phase 2 consumes.
    """
    logger.info(f"Normalising output for doc_id='{doc_id}' parser={parser_used.value}")

    # ── Normalise all sections ───────────────────────────────────────────────
    raw_sections = raw_output.get("sections", [])
    sections = [_normalise_section(s) for s in raw_sections]
    logger.info(f"Normalised {len(sections)} top-level sections.")

    # ── Build flat table list from section tree ──────────────────────────────
    # We use sections (already normalised) not raw all_tables
    # to ensure table objects are consistent ParsedTable instances.
    all_tables = _collect_all_tables(sections)
    logger.info(f"Collected {len(all_tables)} total tables across all sections.")

    # ── Build ParsedDocument ────────────────────────────────────────────────
    doc = ParsedDocument(
        doc_id         = doc_id,
        file_name      = file_name,
        total_pages    = int(raw_output.get("total_pages", 0)),
        parser_used    = parser_used,
        language_hint  = str(raw_output.get("language_hint", "en")),
        sections       = sections,
        all_tables     = all_tables,
        metadata       = metadata or {},
    )

    logger.info(
        f"ParsedDocument ready: {doc.total_pages} pages, "
        f"{len(doc.sections)} sections, {len(doc.all_tables)} tables, "
        f"language='{doc.language_hint}', parser='{doc.parser_used.value}'"
    )

    return doc